-- PostgreSQL compatible tests from crdb_internal_default_privileges
-- 42 tests
-- Most tests are commented out because they rely on CockroachDB-specific crdb_internal schema

SET client_min_messages = warning;
DROP DATABASE IF EXISTS test2;
DROP OWNED BY foo CASCADE;
DROP OWNED BY bar CASCADE;
DROP OWNED BY roach_a CASCADE;
DROP OWNED BY roach_b CASCADE;
DROP OWNED BY roach_c CASCADE;
DROP OWNED BY roach_d CASCADE;
DROP OWNED BY tmp CASCADE;
DROP OWNED BY invalidate CASCADE;
DROP USER IF EXISTS foo;
DROP USER IF EXISTS bar;
DROP ROLE IF EXISTS roach_a;
DROP ROLE IF EXISTS roach_b;
DROP ROLE IF EXISTS roach_c;
DROP ROLE IF EXISTS roach_d;
DROP ROLE IF EXISTS tmp;
DROP ROLE IF EXISTS invalidate;
RESET client_min_messages;

-- Test 1: statement (line 1)
ALTER DEFAULT PRIVILEGES GRANT SELECT ON TABLES TO PUBLIC;
ALTER DEFAULT PRIVILEGES GRANT USAGE ON TYPES TO PUBLIC;
ALTER DEFAULT PRIVILEGES GRANT USAGE ON SCHEMAS TO PUBLIC;
ALTER DEFAULT PRIVILEGES GRANT SELECT ON SEQUENCES TO PUBLIC;

-- Test 2: query (line 7)
-- SELECT * FROM crdb_internal.default_privileges;

-- Test 3: statement (line 107)
CREATE USER foo;

-- Test 4: statement (line 110)
CREATE USER bar;

-- Test 5: statement (line 113)
ALTER DEFAULT PRIVILEGES GRANT ALL ON TABLES TO foo, bar;
ALTER DEFAULT PRIVILEGES GRANT ALL ON TYPES TO foo, bar;
ALTER DEFAULT PRIVILEGES GRANT ALL ON SCHEMAS TO foo, bar;
ALTER DEFAULT PRIVILEGES GRANT ALL ON SEQUENCES TO foo, bar;

-- Test 6: query (line 119)
-- SELECT * FROM crdb_internal.default_privileges WHERE grantee='foo' OR grantee='bar';

-- Test 7: statement (line 172)
-- GRANT foo, bar TO root;

-- Test 8: statement (line 175)
ALTER DEFAULT PRIVILEGES FOR ROLE foo, bar GRANT ALL ON TABLES TO foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE foo, bar GRANT ALL ON TYPES TO foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE foo, bar GRANT ALL ON SCHEMAS TO foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE foo, bar GRANT ALL ON SEQUENCES TO foo, bar;

-- Test 9-42: Various queries on crdb_internal.default_privileges (all commented out)

CREATE DATABASE test2;
\c test2

-- ALTER DEFAULT PRIVILEGES GRANT DROP ON TABLES TO foo;

\c pg_tests

CREATE ROLE roach_a;
CREATE ROLE roach_b;
-- SET ROLE roach_b;
ALTER DEFAULT PRIVILEGES FOR ROLE roach_b GRANT SELECT ON TABLES TO roach_a;
-- SET ROLE root;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT INSERT ON TABLES TO roach_a;

CREATE ROLE tmp;
CREATE ROLE roach_c;
CREATE ROLE roach_d;
CREATE ROLE invalidate;

-- Cleanup
ALTER DEFAULT PRIVILEGES REVOKE ALL ON TABLES FROM foo, bar, PUBLIC;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON TYPES FROM foo, bar, PUBLIC;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON SCHEMAS FROM foo, bar, PUBLIC;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON SEQUENCES FROM foo, bar, PUBLIC;
