-- PostgreSQL compatible tests from create_statements
-- 21 tests

-- CockroachDB has a built-in `crdb_internal.create_statements` virtual table and
-- `SHOW CREATE TABLE`. PostgreSQL doesn't, so we provide a small compatibility
-- shim for the purposes of these tests.
CREATE SCHEMA IF NOT EXISTS crdb_internal;

CREATE OR REPLACE FUNCTION crdb_internal.pg_relation_create_statement(rel regclass)
RETURNS text
LANGUAGE sql
STABLE
AS $$
  WITH r AS (
    SELECT c.oid AS relid, n.nspname, c.relname, c.relpersistence
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.oid = rel
  ),
  cols AS (
    SELECT
      a.attnum,
      format(
        '%I %s%s%s',
        a.attname,
        pg_catalog.format_type(a.atttypid, a.atttypmod),
        CASE
          WHEN a.attidentity = 'a' THEN ' GENERATED ALWAYS AS IDENTITY'
          WHEN a.attidentity = 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY'
          ELSE ''
        END,
        CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END
      ) AS item
    FROM pg_attribute a
    WHERE a.attrelid = rel AND a.attnum > 0 AND NOT a.attisdropped
    ORDER BY a.attnum
  ),
  cons AS (
    SELECT
      100000 + row_number() OVER (ORDER BY c.contype, c.conname) AS attnum,
      format('CONSTRAINT %I %s', c.conname, pg_get_constraintdef(c.oid, true)) AS item
    FROM pg_constraint c
    WHERE c.conrelid = rel AND c.contype IN ('p', 'u', 'f', 'c')
  ),
  items AS (
    SELECT * FROM cols
    UNION ALL
    SELECT * FROM cons
  )
	  SELECT format(
	    'CREATE %sTABLE %I.%I (%s);',
	    CASE WHEN r.relpersistence = 'u' THEN 'UNLOGGED ' ELSE '' END,
	    r.nspname,
	    r.relname,
	    string_agg(item, ', ' ORDER BY attnum)
	  )
	  FROM r, items
	  GROUP BY r.nspname, r.relname, r.relpersistence;
$$;

CREATE OR REPLACE VIEW crdb_internal.create_statements AS
  SELECT
    current_database() AS database_name,
    n.nspname AS schema_name,
    c.relname AS descriptor_name,
    c.oid::int AS descriptor_id,
    crdb_internal.pg_relation_create_statement(c.oid) AS create_statement,
    crdb_internal.pg_relation_create_statement(c.oid) AS create_nofks,
    ARRAY[]::text[] AS fk_statements,
    ARRAY[]::text[] AS validate_statements
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE c.relkind IN ('r', 'p')
UNION ALL
  SELECT
    current_database(),
    n.nspname,
    c.relname,
    c.oid::int,
    pg_get_indexdef(c.oid) || ';',
    pg_get_indexdef(c.oid) || ';',
    ARRAY[]::text[],
    ARRAY[]::text[]
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE c.relkind IN ('i', 'I');

-- Test 1: statement (line 6)
CREATE TABLE t (
  -- CockroachDB has an implicit `rowid` primary key; PostgreSQL requires an
  -- explicit key for a self-referential FK.
  rowid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  a INT REFERENCES t(rowid)
);

-- Test 2: statement (line 18)
CREATE TABLE c (
	a INT NOT NULL,
	b INT NULL
);

CREATE INDEX c_a_b_idx ON c (a ASC, b ASC);

-- Test 3: statement (line 27)
COMMENT ON TABLE c IS 'table';

-- Test 4: statement (line 30)
COMMENT ON COLUMN c.a IS 'column';

-- Test 5: statement (line 33)
COMMENT ON INDEX c_a_b_idx IS 'index';

-- onlyif config schema-locked-disabled

-- Test 6: query (line 37)
SELECT
  regexp_replace(create_statement, '\n', ' ', 'g'),
  regexp_replace(create_nofks, '\n', ' ', 'g'),
  fk_statements,
  validate_statements
FROM
  crdb_internal.create_statements
WHERE
  database_name = current_database()
AND
  schema_name NOT IN ('pg_catalog', 'pg_extension', 'crdb_internal', 'information_schema')
AND
  schema_name NOT LIKE 'pg_toast%'
AND
  schema_name NOT LIKE 'pg_temp%'
ORDER BY schema_name, descriptor_name;

-- Test 7: query (line 57)
SELECT
  regexp_replace(create_statement, '\n', ' ', 'g'),
  regexp_replace(create_nofks, '\n', ' ', 'g'),
  fk_statements,
  validate_statements
FROM
  crdb_internal.create_statements
WHERE
  database_name = current_database()
AND
  schema_name NOT IN ('pg_catalog', 'pg_extension', 'crdb_internal', 'information_schema')
AND
  schema_name NOT LIKE 'pg_toast%'
AND
  schema_name NOT LIKE 'pg_temp%'
ORDER BY schema_name, descriptor_name;

-- Test 8: query (line 76)
CREATE UNLOGGED TABLE unlogged_tbl (col int PRIMARY KEY);

-- Test 9: query (line 82)
SELECT create_statement FROM crdb_internal.create_statements WHERE descriptor_name = 'unlogged_tbl';

-- Test 10: query (line 91)
SELECT create_statement FROM crdb_internal.create_statements WHERE descriptor_name = 'unlogged_tbl';

-- Test 11: statement (line 99)
\set ON_ERROR_STOP 0
CREATE TABLE a (b INT) WITH (foo=100);
\set ON_ERROR_STOP 1

-- Test 12: statement (line 102)
\set ON_ERROR_STOP 0
CREATE TABLE a (b INT) WITH (fillfactor=true);
\set ON_ERROR_STOP 1

-- Test 13: statement (line 105)
\set ON_ERROR_STOP 0
CREATE TABLE a (b INT) WITH (toast_tuple_target=100);
\set ON_ERROR_STOP 1

-- Test 14: query (line 108)
CREATE TABLE a (b INT) WITH (fillfactor=99);

-- Test 15: query (line 113)
CREATE INDEX a_idx ON a(b) WITH (fillfactor=50);

-- Test 16: statement (line 118)
DROP TABLE a CASCADE;

-- Test 17: query (line 121)
CREATE TABLE a (b INT) WITH (autovacuum_enabled=off);

-- Test 18: statement (line 126)
DROP TABLE a CASCADE;

-- Test 19: query (line 129)
CREATE TABLE a (b INT) WITH (autovacuum_enabled=on);

-- Test 20: statement (line 133)
DROP TABLE a CASCADE;

-- Test 21: statement (line 136)
\set ON_ERROR_STOP 0
CREATE TABLE a (b INT) WITH (autovacuum_enabled='11');
\set ON_ERROR_STOP 1
