-- PostgreSQL compatible tests from inverted_filter_geospatial
-- 22 tests

SET client_min_messages = warning;
CREATE EXTENSION IF NOT EXISTS postgis;

-- Test 1: statement (line 4)
CREATE TABLE geo_table(
  k int primary key,
  geom geometry
);
CREATE INDEX geo_table_geom_index ON geo_table USING GIST (geom);

-- Test 2: statement (line 11)
INSERT INTO geo_table VALUES
  (1, 'POINT(1.0 1.0)'),
  (2, 'LINESTRING(1.0 1.0, 2.0 2.0)'),
  (3, 'POINT(3.0 3.0)'),
  (4, 'LINESTRING(4.0 4.0, 5.0 5.0)'),
  (5, 'LINESTRING(40.0 40.0, 41.0 41.0)'),
  (6, 'POLYGON((1.0 1.0, 5.0 1.0, 5.0 5.0, 1.0 5.0, 1.0 1.0))');

-- Test 3: query (line 20)
SELECT k FROM geo_table WHERE ST_Intersects('POINT(3.0 3.0)'::geometry, geom) ORDER BY k;

-- Test 4: query (line 26)
SELECT k FROM geo_table WHERE ST_Intersects('POINT(4.5 4.5)'::geometry, geom) ORDER BY k;

-- Test 5: query (line 32)
SELECT k FROM geo_table WHERE ST_CoveredBy('POINT(4.0 4.5)'::geometry, geom) ORDER BY k;

-- Test 6: query (line 37)
SELECT k FROM geo_table WHERE ST_Intersects('POINT(2.5 2.5)'::geometry, geom) ORDER BY k;

-- Test 7: query (line 42)
SELECT k FROM geo_table WHERE ST_DWithin('POINT(2.5 2.5)'::geometry, geom, 1) ORDER BY k;

-- Test 8: query (line 53)
SELECT k FROM geo_table WHERE 'POINT(3.0 3.0)'::geometry && geom ORDER BY k;

-- Test 9: query (line 59)
SELECT k FROM geo_table WHERE 'POINT(3.0 3.0)'::geometry::box2d && geom ORDER BY k;

-- Test 10: query (line 65)
SELECT k FROM geo_table WHERE ST_Covers('LINESTRING(1.0 1.0, 5.0 5.0)'::geometry, geom) ORDER BY k;

-- Test 11: query (line 75)
SELECT k FROM geo_table WHERE 'LINESTRING(1.0 1.0, 5.0 5.0)'::geometry ~ geom ORDER BY k;

-- Test 12: query (line 84)
SELECT k FROM geo_table WHERE 'LINESTRING(1.0 1.0, 5.0 5.0)'::geometry::box2d ~ geom ORDER BY k;

-- Test 13: query (line 93)
SELECT k FROM geo_table WHERE geom ~ 'LINESTRING(1.0 1.0, 5.0 5.0)'::geometry ORDER BY k;

-- Test 14: query (line 98)
SELECT k FROM geo_table WHERE geom ~ 'LINESTRING(1.0 1.0, 5.0 5.0)'::geometry::box2d ORDER BY k;

-- Test 15: statement (line 103)
CREATE TABLE geo_table2(
  k int,
  geom geometry,
  k_plus_one int,
  PRIMARY KEY (k, k_plus_one)
);
CREATE INDEX geo_table2_geom_index ON geo_table2 USING GIST (geom);

-- Test 16: statement (line 112)
INSERT INTO geo_table2 VALUES
  (1, 'LINESTRING(1.0 1.0, 2.0 2.0)', 2),
  (2, 'POLYGON((1.0 1.0, 5.0 1.0, 5.0 5.0, 1.0 5.0, 1.0 1.0))', 3);

-- Test 17: query (line 117)
SELECT k FROM geo_table2 WHERE ST_Intersects('POINT(3.0 3.0)'::geometry, geom);

-- Test 18: query (line 122)
SELECT k, k_plus_one FROM geo_table2 WHERE ST_Intersects('POINT(3.0 3.0)'::geometry, geom);

-- Test 19: query (line 127)
SELECT k, k_plus_one, geom FROM geo_table2 WHERE ST_Intersects('POINT(3.0 3.0)'::geometry, geom);

-- Test 20: statement (line 133)
CREATE TABLE relatedapp_location (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "point" GEOMETRY(POINT,4326) NOT NULL,
    CONSTRAINT relatedapp_location_pkey PRIMARY KEY (id)
);
CREATE INDEX relatedapp_location_point_id ON relatedapp_location USING GIST ("point");

-- Test 21: statement (line 142)
CREATE TABLE relatedapp_city (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    state VARCHAR(2) NOT NULL,
    location_id BIGINT NOT NULL,
    CONSTRAINT relatedapp_city_pkey PRIMARY KEY (id),
    CONSTRAINT relatedapp_city_location_id_ac4f6573_fk_relatedapp_location_id FOREIGN KEY (location_id) REFERENCES relatedapp_location(id)
);

-- Test 22: query (line 153)
SELECT "relatedapp_city"."id", "relatedapp_city"."name", "relatedapp_city"."state", "relatedapp_city"."location_id"
FROM "relatedapp_city" INNER JOIN "relatedapp_location"
ON ("relatedapp_city"."location_id" = "relatedapp_location"."id")
WHERE (ST_Within("relatedapp_location"."point", ST_GeomFromEWKB('\x0103000020e6100000010000002100000060200890a15a58c087a3ab7477874040e7ee440bc15a58c05dff0b2ff8844040431645471e5b58c0654d8a7a918240400cb7ccaeb55b58c0f79094f65a804040ed065a70815c58c0d5a382686a7e40407efd62b7795d58c0130468e5d27c4040b5db5df9945e58c082c25816a47b4040b1b49e53c85f58c0c873589ee97a4040c6866ef6076158c0bad6dea7aa7a4040db583e99476258c0c873589ee97a4040d7317ff37a6358c082c25816a47b40400e107a35966458c0130468e5d27c40409f06837c8e6558c0d5a382686a7e40408056103e5a6658c0f79094f65a80404049f797a5f16658c0654d8a7a91824040a51e98e14e6758c05dff0b2ff88440402cedd45c6e6758c087a3ab7477874040a51e98e14e6758c0b1474bbaf689404049f797a5f16658c0a9f9cc6e5d8c40408056103e5a6658c017b6c2f2938e40409f06837c8e6558c038a3d480849040400e107a35966458c0fb42ef031c924040d7317ff37a6358c08c84fed24a934040db583e99476258c046d3fe4a05944040c6866ef6076158c05470784144944040b1b49e53c85f58c046d3fe4a05944040b5db5df9945e58c08c84fed24a9340407efd62b7795d58c0fb42ef031c924040ed065a70815c58c039a3d480849040400cb7ccaeb55b58c017b6c2f2938e4040431645471e5b58c0a9f9cc6e5d8c4040e7ee440bc15a58c0b1474bbaf689404060200890a15a58c087a3ab7477874040'::bytea))
  OR ST_Within("relatedapp_location"."point", ST_GeomFromEWKB('\x0103000020e610000001000000210000008a230f4416d753c0f2cd3637a617444011f24bbf35d753c0c82997f1261544406d194cfb92d753c0d077153dc012444036bad3622ad853c062bb1fb989104440170a6124f6d853c040ce0d2b990e4440a8006a6beed953c07e2ef3a7010d4440dfde64ad09db53c0edece3d8d20b4440dbb7a5073ddc53c0339ee360180b4440f08975aa7cdd53c025016a6ad90a4440055c454dbcde53c0339ee360180b4440013586a7efdf53c0edece3d8d20b4440381381e90ae153c07e2ef3a7010d4440c9098a3003e253c040ce0d2b990e4440aa5917f2cee253c062bb1fb98910444073fa9e5966e353c0d077153dc0124440cf219f95c3e353c0c82997f12615444056f0db10e3e353c0f2cd3637a6174440cf219f95c3e353c01c72d67c251a444073fa9e5966e353c0142458318c1c4440aa5917f2cee253c082e04db5c21e4440c9098a3003e253c0a3cd5f43b3204440381381e90ae153c0666d7ac64a224440013586a7efdf53c0f7ae899579234440055c454dbcde53c0b1fd890d34244440f08975aa7cdd53c0bf9a030473244440dbb7a5073ddc53c0b1fd890d34244440dfde64ad09db53c0f7ae899579234440a8006a6beed953c0666d7ac64a224440170a6124f6d853c0a4cd5f43b320444036bad3622ad853c082e04db5c21e44406d194cfb92d753c0142458318c1c444011f24bbf35d753c01c72d67c251a44408a230f4416d753c0f2cd3637a6174440'::bytea)));

RESET client_min_messages;
