-- PostgreSQL compatible tests from pg_catalog_pg_default_acl
-- 38 tests

SET client_min_messages = warning;

-- Roles are cluster-level objects; clean up for repeatable runs.
DROP ROLE IF EXISTS foo;
DROP ROLE IF EXISTS bar;
DROP ROLE IF EXISTS testuser;

-- Avoid unstable OIDs from pg_default_acl output.
CREATE OR REPLACE VIEW v_default_acl AS
SELECT
  r.rolname AS defaclrole,
  COALESCE(n.nspname, '<global>') AS defaclnamespace,
  d.defaclobjtype,
  d.defaclacl
FROM pg_catalog.pg_default_acl d
JOIN pg_catalog.pg_roles r ON r.oid = d.defaclrole
LEFT JOIN pg_catalog.pg_namespace n ON n.oid = d.defaclnamespace;

-- Test 1: statement (line 1)
ALTER DEFAULT PRIVILEGES GRANT SELECT ON TABLES TO PUBLIC;
ALTER DEFAULT PRIVILEGES GRANT USAGE ON SCHEMAS TO PUBLIC;
ALTER DEFAULT PRIVILEGES GRANT SELECT ON SEQUENCES TO PUBLIC;
ALTER DEFAULT PRIVILEGES REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;

-- Test 2: query (line 8)
SELECT * FROM v_default_acl
ORDER BY defaclrole, defaclnamespace, defaclobjtype, defaclacl::TEXT;

-- Test 3: statement (line 17)
ALTER DEFAULT PRIVILEGES GRANT EXECUTE ON FUNCTIONS TO PUBLIC;

-- Test 4: statement (line 20)
CREATE USER foo;

-- Test 5: statement (line 23)
CREATE USER bar;

-- Test 6: statement (line 26)
ALTER DEFAULT PRIVILEGES GRANT ALL ON TABLES TO foo, bar WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES GRANT ALL ON TYPES TO foo, bar WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES GRANT ALL ON SCHEMAS TO foo, bar WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES GRANT ALL ON SEQUENCES TO foo, bar WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES GRANT ALL ON FUNCTIONS TO foo, bar WITH GRANT OPTION;

-- Test 7: query (line 33)
SELECT * FROM v_default_acl
ORDER BY defaclrole, defaclnamespace, defaclobjtype, defaclacl::TEXT;

-- Test 8: statement (line 43)
GRANT foo, bar TO pan;

-- Test 9: statement (line 46)
ALTER DEFAULT PRIVILEGES FOR ROLE foo GRANT ALL ON TABLES TO foo, bar WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE bar GRANT ALL ON TABLES TO foo, bar WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE foo GRANT ALL ON TYPES TO foo, bar WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE bar GRANT ALL ON TYPES TO foo, bar WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE foo GRANT ALL ON SCHEMAS TO foo, bar WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE bar GRANT ALL ON SCHEMAS TO foo, bar WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE foo GRANT ALL ON SEQUENCES TO foo, bar WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE bar GRANT ALL ON SEQUENCES TO foo, bar WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE foo GRANT ALL ON FUNCTIONS TO foo, bar WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE bar GRANT ALL ON FUNCTIONS TO foo, bar WITH GRANT OPTION;

-- Test 10: query (line 54)
SELECT * FROM v_default_acl
ORDER BY defaclrole, defaclnamespace, defaclobjtype, defaclacl::TEXT;

-- Test 11: statement (line 74)
ALTER DEFAULT PRIVILEGES FOR ROLE foo REVOKE ALL ON TABLES FROM foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE bar REVOKE ALL ON TABLES FROM foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE foo REVOKE ALL ON TYPES FROM foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE bar REVOKE ALL ON TYPES FROM foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE foo REVOKE ALL ON SCHEMAS FROM foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE bar REVOKE ALL ON SCHEMAS FROM foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE foo REVOKE ALL ON SEQUENCES FROM foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE bar REVOKE ALL ON SEQUENCES FROM foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE foo REVOKE ALL ON FUNCTIONS FROM foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE bar REVOKE ALL ON FUNCTIONS FROM foo, bar;

-- Test 12: query (line 83)
SELECT * FROM v_default_acl
ORDER BY defaclrole, defaclnamespace, defaclobjtype, defaclacl::TEXT;

-- Test 13: statement (line 103)
ALTER DEFAULT PRIVILEGES FOR ROLE foo GRANT ALL ON TABLES TO foo WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE foo GRANT ALL ON SEQUENCES TO foo WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE foo GRANT ALL ON SCHEMAS TO foo WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE foo GRANT ALL ON TYPES TO foo WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE foo GRANT ALL ON FUNCTIONS TO foo WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE bar GRANT ALL ON TABLES TO bar WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE bar GRANT ALL ON SEQUENCES TO bar WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE bar GRANT ALL ON SCHEMAS TO bar WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE bar GRANT ALL ON TYPES TO bar WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE bar GRANT ALL ON FUNCTIONS TO bar WITH GRANT OPTION;

-- Test 14: query (line 117)
SELECT * FROM v_default_acl
ORDER BY defaclrole, defaclnamespace, defaclobjtype, defaclacl::TEXT;

-- Test 15: statement (line 139)
ALTER DEFAULT PRIVILEGES FOR ROLE foo REVOKE SELECT ON TABLES FROM foo;

-- Test 16: query (line 142)
SELECT * FROM v_default_acl
ORDER BY defaclrole, defaclnamespace, defaclobjtype, defaclacl::TEXT;

-- Test 17: statement (line 162)
ALTER DEFAULT PRIVILEGES FOR ROLE foo GRANT SELECT ON TABLES TO foo;

-- Test 18: query (line 165)
SELECT * FROM v_default_acl
ORDER BY defaclrole, defaclnamespace, defaclobjtype, defaclacl::TEXT;

-- Test 19: statement (line 185)
ALTER DEFAULT PRIVILEGES REVOKE SELECT ON TABLES FROM foo, bar, public;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON SCHEMAS FROM foo, bar, public;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON SEQUENCES FROM foo, bar, public;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON FUNCTIONS FROM foo, bar, public;

-- Test 20: statement (line 191)
ALTER DEFAULT PRIVILEGES REVOKE ALL ON TYPES FROM foo, bar;

-- Test 21: query (line 194)
SELECT * FROM v_default_acl
ORDER BY defaclrole, defaclnamespace, defaclobjtype, defaclacl::TEXT;

-- Test 22: statement (line 212)
ALTER DEFAULT PRIVILEGES REVOKE ALL ON TABLES FROM foo, bar, public;
ALTER DEFAULT PRIVILEGES GRANT UPDATE, DELETE ON TABLES TO foo;

-- Test 23: query (line 216)
SELECT * FROM v_default_acl
ORDER BY defaclrole, defaclnamespace, defaclobjtype, defaclacl::TEXT;

-- Test 24: statement (line 233)
ALTER DEFAULT PRIVILEGES REVOKE UPDATE, DELETE ON TABLES FROM foo;

-- Test 25: statement (line 238)
ALTER DEFAULT PRIVILEGES FOR ROLE foo GRANT ALL ON TABLES TO foo, bar WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE bar GRANT ALL ON TABLES TO foo, bar WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE foo GRANT ALL ON TYPES TO foo, bar WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE bar GRANT ALL ON TYPES TO foo, bar WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE foo GRANT ALL ON SCHEMAS TO foo, bar WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE bar GRANT ALL ON SCHEMAS TO foo, bar WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE foo GRANT ALL ON SEQUENCES TO foo, bar WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE bar GRANT ALL ON SEQUENCES TO foo, bar WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE foo GRANT ALL ON FUNCTIONS TO foo, bar WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE bar GRANT ALL ON FUNCTIONS TO foo, bar WITH GRANT OPTION;

-- Test 26: query (line 245)
SELECT * FROM v_default_acl
ORDER BY defaclrole, defaclnamespace, defaclobjtype, defaclacl::TEXT;

-- Test 27: statement (line 266)
ALTER DEFAULT PRIVILEGES FOR ROLE foo REVOKE ALL ON TABLES FROM foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE bar REVOKE ALL ON TABLES FROM foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE foo REVOKE ALL ON TYPES FROM foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE bar REVOKE ALL ON TYPES FROM foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE foo REVOKE ALL ON SCHEMAS FROM foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE bar REVOKE ALL ON SCHEMAS FROM foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE foo REVOKE ALL ON SEQUENCES FROM foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE bar REVOKE ALL ON SEQUENCES FROM foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE foo REVOKE ALL ON FUNCTIONS FROM foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE bar REVOKE ALL ON FUNCTIONS FROM foo, bar;

-- Test 28: query (line 273)
SELECT * FROM v_default_acl
ORDER BY defaclrole, defaclnamespace, defaclobjtype, defaclacl::TEXT;

-- Test 29: statement (line 291)
CREATE USER testuser;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON TABLES FROM testuser;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON SEQUENCES FROM testuser;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON SCHEMAS FROM testuser;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON TYPES FROM testuser;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON FUNCTIONS FROM testuser;

-- Test 30: query (line 300)
SELECT * FROM v_default_acl
ORDER BY defaclrole, defaclnamespace, defaclobjtype, defaclacl::TEXT;

-- Test 31: statement (line 321)
ALTER DEFAULT PRIVILEGES REVOKE USAGE ON TYPES FROM public;

-- Test 32: query (line 325)
SELECT * FROM v_default_acl
ORDER BY defaclrole, defaclnamespace, defaclobjtype, defaclacl::TEXT;

-- Test 33: statement (line 347)
ALTER DEFAULT PRIVILEGES GRANT ALL ON TYPES TO testuser WITH GRANT OPTION;

-- Test 34: query (line 352)
SELECT * FROM v_default_acl
ORDER BY defaclrole, defaclnamespace, defaclobjtype, defaclacl::TEXT;

-- Test 35: statement (line 373)
ALTER DEFAULT PRIVILEGES GRANT ALL ON TABLES TO foo WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES GRANT ALL ON SEQUENCES TO foo WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES GRANT ALL ON SCHEMAS TO foo WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES GRANT ALL ON TYPES TO foo WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES GRANT ALL ON FUNCTIONS TO foo WITH GRANT OPTION;

-- Test 36: query (line 382)
SELECT * FROM v_default_acl
ORDER BY defaclrole, defaclnamespace, defaclobjtype, defaclacl::TEXT;

-- Test 37: statement (line 403)
ALTER DEFAULT PRIVILEGES IN SCHEMA PUBLIC GRANT SELECT,UPDATE,INSERT,DELETE ON TABLES TO foo;
ALTER DEFAULT PRIVILEGES IN SCHEMA PUBLIC GRANT ALL ON SEQUENCES TO foo;
ALTER DEFAULT PRIVILEGES IN SCHEMA PUBLIC GRANT ALL ON TYPES TO foo;
ALTER DEFAULT PRIVILEGES IN SCHEMA PUBLIC GRANT ALL ON FUNCTIONS TO foo;

-- Test 38: query (line 411)
SELECT * FROM v_default_acl
WHERE defaclnamespace <> '<global>'
ORDER BY defaclrole, defaclnamespace, defaclobjtype, defaclacl::TEXT;

RESET client_min_messages;
