-- PostgreSQL compatible tests from pg_catalog_pg_default_acl_with_grant_option
-- 65 tests

-- Test 1: statement (line 1)
ALTER DEFAULT PRIVILEGES GRANT SELECT ON TABLES TO PUBLIC WITH GRANT OPTION

-- Test 2: statement (line 4)
ALTER DEFAULT PRIVILEGES GRANT USAGE ON SCHEMAS TO PUBLIC WITH GRANT OPTION

-- Test 3: statement (line 7)
ALTER DEFAULT PRIVILEGES GRANT SELECT ON SEQUENCES TO PUBLIC WITH GRANT OPTION

-- Test 4: statement (line 10)
ALTER DEFAULT PRIVILEGES GRANT SELECT ON TABLES TO PUBLIC;

-- Test 5: statement (line 13)
ALTER DEFAULT PRIVILEGES GRANT USAGE ON SCHEMAS TO PUBLIC;

-- Test 6: statement (line 16)
ALTER DEFAULT PRIVILEGES GRANT SELECT ON SEQUENCES TO PUBLIC;

-- Test 7: query (line 20)
SELECT * FROM PG_CATALOG.PG_DEFAULT_ACL

-- Test 8: statement (line 28)
CREATE USER foo

-- Test 9: statement (line 31)
CREATE USER bar

-- Test 10: statement (line 34)
ALTER DEFAULT PRIVILEGES GRANT ALL ON TABLES TO foo, bar WITH GRANT OPTION;

-- Test 11: statement (line 37)
ALTER DEFAULT PRIVILEGES GRANT ALL ON TYPES TO foo, bar WITH GRANT OPTION;

-- Test 12: statement (line 40)
ALTER DEFAULT PRIVILEGES GRANT ALL ON SCHEMAS TO foo, bar WITH GRANT OPTION;

-- Test 13: statement (line 43)
ALTER DEFAULT PRIVILEGES GRANT ALL ON SEQUENCES TO foo, bar WITH GRANT OPTION;

-- Test 14: statement (line 46)
ALTER DEFAULT PRIVILEGES GRANT ALL ON FUNCTIONS TO foo, bar WITH GRANT OPTION;

-- Test 15: query (line 49)
SELECT * FROM PG_CATALOG.PG_DEFAULT_ACL

-- Test 16: statement (line 59)
ALTER DEFAULT PRIVILEGES REVOKE GRANT OPTION FOR SELECT, DELETE ON TABLES FROM foo, bar;

-- Test 17: statement (line 62)
ALTER DEFAULT PRIVILEGES REVOKE GRANT OPTION FOR USAGE ON TYPES FROM foo, bar;

-- Test 18: statement (line 65)
ALTER DEFAULT PRIVILEGES REVOKE GRANT OPTION FOR CREATE ON SCHEMAS FROM foo, bar;

-- Test 19: statement (line 68)
ALTER DEFAULT PRIVILEGES REVOKE GRANT OPTION FOR CREATE, UPDATE ON SEQUENCES FROM foo, bar;

-- Test 20: statement (line 71)
ALTER DEFAULT PRIVILEGES REVOKE GRANT OPTION FOR EXECUTE ON FUNCTIONS FROM foo, bar;

-- Test 21: query (line 74)
SELECT * FROM PG_CATALOG.PG_DEFAULT_ACL

-- Test 22: statement (line 84)
ALTER DEFAULT PRIVILEGES REVOKE GRANT OPTION FOR ALL ON TABLES FROM foo, bar;

-- Test 23: statement (line 87)
ALTER DEFAULT PRIVILEGES REVOKE GRANT OPTION FOR ALL ON TYPES FROM foo, bar;

-- Test 24: statement (line 90)
ALTER DEFAULT PRIVILEGES REVOKE GRANT OPTION FOR ALL ON SCHEMAS FROM foo, bar;

-- Test 25: statement (line 93)
ALTER DEFAULT PRIVILEGES REVOKE GRANT OPTION FOR ALL ON SEQUENCES FROM foo, bar;

-- Test 26: statement (line 96)
ALTER DEFAULT PRIVILEGES REVOKE GRANT OPTION FOR ALL ON FUNCTIONS FROM foo, bar;

-- Test 27: query (line 99)
SELECT * FROM PG_CATALOG.PG_DEFAULT_ACL

-- Test 28: statement (line 109)
GRANT foo, bar TO root;

-- Test 29: statement (line 112)
ALTER DEFAULT PRIVILEGES FOR ROLE foo, bar GRANT ALL ON TABLES TO foo, bar WITH GRANT OPTION;

-- Test 30: statement (line 115)
ALTER DEFAULT PRIVILEGES FOR ROLE foo, bar GRANT ALL ON TYPES TO foo, bar WITH GRANT OPTION;

-- Test 31: statement (line 118)
ALTER DEFAULT PRIVILEGES FOR ROLE foo, bar GRANT ALL ON SCHEMAS TO foo, bar WITH GRANT OPTION;

-- Test 32: statement (line 121)
ALTER DEFAULT PRIVILEGES FOR ROLE foo, bar GRANT ALL ON SEQUENCES TO foo, bar WITH GRANT OPTION;

-- Test 33: statement (line 124)
ALTER DEFAULT PRIVILEGES FOR ROLE foo, bar GRANT ALL ON FUNCTIONS TO foo, bar WITH GRANT OPTION;

-- Test 34: query (line 128)
SELECT * FROM PG_CATALOG.PG_DEFAULT_ACL

-- Test 35: statement (line 148)
ALTER DEFAULT PRIVILEGES FOR ROLE foo, bar REVOKE ALL ON TABLES FROM foo, bar;

-- Test 36: statement (line 151)
ALTER DEFAULT PRIVILEGES FOR ROLE foo, bar REVOKE ALL ON TYPES FROM foo, bar;

-- Test 37: statement (line 154)
ALTER DEFAULT PRIVILEGES FOR ROLE foo, bar REVOKE ALL ON SCHEMAS FROM foo, bar;

-- Test 38: statement (line 157)
ALTER DEFAULT PRIVILEGES FOR ROLE foo, bar REVOKE ALL ON SEQUENCES FROM foo, bar;

-- Test 39: statement (line 160)
ALTER DEFAULT PRIVILEGES FOR ROLE foo, bar REVOKE ALL ON FUNCTIONS FROM foo, bar;

-- Test 40: query (line 165)
SELECT * FROM PG_CATALOG.PG_DEFAULT_ACL

-- Test 41: statement (line 185)
ALTER DEFAULT PRIVILEGES FOR ROLE foo GRANT ALL ON TABLES TO foo;

-- Test 42: statement (line 188)
ALTER DEFAULT PRIVILEGES FOR ROLE foo GRANT ALL ON SEQUENCES TO foo;

-- Test 43: statement (line 191)
ALTER DEFAULT PRIVILEGES FOR ROLE foo GRANT ALL ON SCHEMAS TO foo;

-- Test 44: statement (line 194)
ALTER DEFAULT PRIVILEGES FOR ROLE foo GRANT ALL ON TYPES TO foo;

-- Test 45: statement (line 197)
ALTER DEFAULT PRIVILEGES FOR ROLE foo GRANT ALL ON FUNCTIONS TO foo;

-- Test 46: statement (line 200)
ALTER DEFAULT PRIVILEGES FOR ROLE bar GRANT ALL ON TABLES TO bar;

-- Test 47: statement (line 203)
ALTER DEFAULT PRIVILEGES FOR ROLE bar GRANT ALL ON SEQUENCES TO bar;

-- Test 48: statement (line 206)
ALTER DEFAULT PRIVILEGES FOR ROLE bar GRANT ALL ON SCHEMAS TO bar;

-- Test 49: statement (line 209)
ALTER DEFAULT PRIVILEGES FOR ROLE bar GRANT ALL ON TYPES TO bar;

-- Test 50: statement (line 212)
ALTER DEFAULT PRIVILEGES FOR ROLE bar GRANT ALL ON FUNCTIONS TO bar;

-- Test 51: statement (line 216)
ALTER DEFAULT PRIVILEGES FOR ROLE foo REVOKE GRANT OPTION FOR ALL ON TABLES FROM foo;

-- Test 52: statement (line 219)
ALTER DEFAULT PRIVILEGES FOR ROLE foo REVOKE GRANT OPTION FOR ALL ON SEQUENCES FROM foo;

-- Test 53: statement (line 222)
ALTER DEFAULT PRIVILEGES FOR ROLE foo REVOKE GRANT OPTION FOR ALL ON SCHEMAS FROM foo;

-- Test 54: statement (line 225)
ALTER DEFAULT PRIVILEGES FOR ROLE foo REVOKE GRANT OPTION FOR ALL ON TYPES FROM foo;

-- Test 55: statement (line 228)
ALTER DEFAULT PRIVILEGES FOR ROLE foo REVOKE GRANT OPTION FOR ALL ON FUNCTIONS FROM foo;

-- Test 56: statement (line 231)
ALTER DEFAULT PRIVILEGES FOR ROLE bar REVOKE GRANT OPTION FOR ALL ON TABLES FROM bar;

-- Test 57: statement (line 234)
ALTER DEFAULT PRIVILEGES FOR ROLE bar REVOKE GRANT OPTION FOR ALL ON SEQUENCES FROM bar;

-- Test 58: statement (line 237)
ALTER DEFAULT PRIVILEGES FOR ROLE bar REVOKE GRANT OPTION FOR ALL ON SCHEMAS FROM bar;

-- Test 59: statement (line 240)
ALTER DEFAULT PRIVILEGES FOR ROLE bar REVOKE GRANT OPTION FOR ALL ON TYPES FROM bar;

-- Test 60: statement (line 243)
ALTER DEFAULT PRIVILEGES FOR ROLE bar REVOKE GRANT OPTION FOR ALL ON FUNCTIONS FROM bar;

-- Test 61: query (line 248)
SELECT * FROM PG_CATALOG.PG_DEFAULT_ACL

-- Test 62: statement (line 258)
ALTER DEFAULT PRIVILEGES FOR ROLE foo GRANT USAGE ON TYPES TO foo WITH GRANT OPTION

-- Test 63: query (line 262)
SELECT * FROM PG_CATALOG.PG_DEFAULT_ACL

-- Test 64: statement (line 273)
ALTER DEFAULT PRIVILEGES FOR ROLE foo REVOKE GRANT OPTION FOR USAGE ON TYPES FROM foo

-- Test 65: query (line 277)
SELECT * FROM PG_CATALOG.PG_DEFAULT_ACL

