-- PostgreSQL compatible tests from show_default_privileges
-- 40 tests

-- Test 1: query (line 3)
SHOW DEFAULT PRIVILEGES

-- Test 2: statement (line 17)
ALTER DEFAULT PRIVILEGES REVOKE ALL ON TABLES FROM root;
ALTER DEFAULT PRIVILEGES REVOKE USAGE ON TYPES FROM public;

-- Test 3: query (line 21)
SHOW DEFAULT PRIVILEGES

-- Test 4: statement (line 31)
ALTER DEFAULT PRIVILEGES GRANT SELECT ON TABLES TO PUBLIC;
ALTER DEFAULT PRIVILEGES GRANT USAGE ON TYPES TO PUBLIC;
ALTER DEFAULT PRIVILEGES GRANT USAGE ON SCHEMAS TO PUBLIC;
ALTER DEFAULT PRIVILEGES GRANT SELECT ON SEQUENCES TO PUBLIC;

-- Test 5: query (line 37)
SHOW DEFAULT PRIVILEGES

-- Test 6: statement (line 51)
CREATE USER foo

-- Test 7: statement (line 54)
CREATE USER bar

-- Test 8: query (line 57)
SHOW DEFAULT PRIVILEGES

-- Test 9: statement (line 71)
ALTER DEFAULT PRIVILEGES GRANT ALL ON TABLES TO foo, bar;
ALTER DEFAULT PRIVILEGES GRANT ALL ON TYPES TO foo, bar;
ALTER DEFAULT PRIVILEGES GRANT ALL ON SCHEMAS TO foo, bar;
ALTER DEFAULT PRIVILEGES GRANT ALL ON SEQUENCES TO foo, bar;

-- Test 10: query (line 77)
SHOW DEFAULT PRIVILEGES FOR ROLE foo, bar, root

-- Test 11: statement (line 113)
GRANT foo, bar TO root;

-- Test 12: statement (line 116)
ALTER DEFAULT PRIVILEGES FOR ROLE foo, bar GRANT ALL ON TABLES TO foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE foo, bar GRANT ALL ON TYPES TO foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE foo, bar GRANT ALL ON SCHEMAS TO foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE foo, bar GRANT ALL ON SEQUENCES TO foo, bar;

-- Test 13: query (line 122)
SHOW DEFAULT PRIVILEGES

-- Test 14: statement (line 144)
ALTER DEFAULT PRIVILEGES FOR ROLE foo, bar REVOKE ALL ON TABLES FROM foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE foo, bar REVOKE ALL ON TYPES FROM foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE foo, bar REVOKE ALL ON SCHEMAS FROM foo, bar;
ALTER DEFAULT PRIVILEGES FOR ROLE foo, bar REVOKE ALL ON SEQUENCES FROM foo, bar;

-- Test 15: query (line 150)
SHOW DEFAULT PRIVILEGES

-- Test 16: statement (line 172)
ALTER DEFAULT PRIVILEGES REVOKE SELECT ON TABLES FROM foo, bar, public;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON TYPES FROM foo, bar, public;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON SCHEMAS FROM foo, bar, public;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON SEQUENCES FROM foo, bar, public;

-- Test 17: query (line 178)
SHOW DEFAULT PRIVILEGES

-- Test 18: statement (line 210)
ALTER DEFAULT PRIVILEGES REVOKE ALL ON TABLES FROM foo, bar, public;
ALTER DEFAULT PRIVILEGES GRANT DROP, ZONECONFIG ON TABLES TO foo WITH GRANT OPTION;

-- Test 19: query (line 214)
SHOW DEFAULT PRIVILEGES

-- Test 20: statement (line 227)
CREATE DATABASE test2;
use test2;
CREATE USER testuser2;

-- Test 21: statement (line 232)
ALTER DEFAULT PRIVILEGES FOR ROLE testuser GRANT DROP, ZONECONFIG ON TABLES TO foo WITH GRANT OPTION;

-- Test 22: query (line 235)
SHOW DEFAULT PRIVILEGES FOR ROLE testuser

-- Test 23: query (line 251)
SHOW DEFAULT PRIVILEGES

-- Test 24: query (line 265)
SHOW DEFAULT PRIVILEGES FOR ROLE testuser

-- Test 25: statement (line 279)
ALTER DEFAULT PRIVILEGES FOR ROLE root GRANT DROP, ZONECONFIG ON TABLES TO foo WITH GRANT OPTION;

-- Test 26: query (line 282)
SHOW DEFAULT PRIVILEGES FOR ROLE root, testuser

-- Test 27: statement (line 305)
ALTER DEFAULT PRIVILEGES FOR ALL ROLES GRANT DROP, ZONECONFIG ON TABLES TO foo WITH GRANT OPTION;

-- Test 28: query (line 309)
SHOW DEFAULT PRIVILEGES FOR ALL ROLES

-- Test 29: statement (line 318)
CREATE DATABASE "MixedCaseDB"

-- Test 30: statement (line 321)
CREATE SCHEMA "MixedCaseDB"."MixedCaseSchema"

-- Test 31: statement (line 324)
USE "MixedCaseDB"

-- Test 32: statement (line 327)
ALTER DEFAULT PRIVILEGES IN SCHEMA "MixedCaseSchema" GRANT SELECT ON TABLES TO foo WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA "MixedCaseSchema" GRANT ALL ON TABLES TO bar;

-- Test 33: query (line 331)
SHOW DEFAULT PRIVILEGES

-- Test 34: query (line 343)
SHOW DEFAULT PRIVILEGES IN SCHEMA "MixedCaseSchema"

-- Test 35: statement (line 350)
ALTER DEFAULT PRIVILEGES FOR ROLE root GRANT SELECT ON TABLES TO testuser;

-- Test 36: query (line 353)
SHOW DEFAULT PRIVILEGES

-- Test 37: query (line 366)
SHOW DEFAULT PRIVILEGES FOR GRANTEE testuser

-- Test 38: statement (line 377)
ALTER DEFAULT PRIVILEGES FOR ALL ROLES GRANT DROP, ZONECONFIG ON TABLES TO foo, bar WITH GRANT OPTION;

-- Test 39: query (line 380)
SHOW DEFAULT PRIVILEGES FOR GRANTEE foo, bar

-- Test 40: query (line 399)
SHOW DEFAULT PRIVILEGES FOR GRANTEE foo IN SCHEMA "MixedCaseSchema"

